apiVersion: v1
kind: Service
metadata:
  name: lcbo-ingester-bridge-service
  labels:
    app: lcbo-ingester-bridge
spec:
  selector:
    app: lcbo-ingester-bridge
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 8080 # Port your application is running on
#  type: ClusterIP
  clusterIP: None
