apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - protocol: TCP
    port: 9092 # Port exposed by Kafka
    targetPort: 9092 # Port Kafka is running on
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest # Use the Kafka image from Confluent
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092 # Kafka broker port
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181" # ZooKeeper address
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092" # Kafka address
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1" # Replication factor for Kafka internal topics

