apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest # Use the ZooKeeper image from Confluent
        ports:
        - containerPort: 2181 # ZooKeeper client port
        - containerPort: 2888 # ZooKeeper peer port
        - containerPort: 3888 # ZooKeeper leader election port
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181" # ZooKeeper client port